[package]
name = "sdf-playground-common"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.13.1", features = ["derive", "min_const_generics"] }
glam = { version = "0.24", default-features = false, features = ["bytemuck"] }
